# class 2 

Date: 25th jan

In [1]:
my_string= "hello world"

In [3]:
print (my_string)

hello world


In [5]:
my_string[1]

'e'

my_string[2:4]
# playing with slices
syntax of slice: 'my_string [start:end]'


In [7]:
my_string[2:4]

'll'

In [8]:
len(my_string)

11

In [10]:
my_string[0:10]

'hello worl'

To access last element, use index -1


In [ ]:
my_string[0:-1]

you can also do slices as: start:end:step..and a -1 step goes backwards

In [13]:
my_string[::-1]

'dlrow olleh'

In [14]:
x="banana"

In [15]:
print (x)

banana


In [16]:
print (x[1], x[5])

a a


In [17]:
x[1:4
]

'ana'

In [18]:
x[3:6]

'ana'

## slicing of numpy array 
arrays are essential data structure in numerical computing! They are available to you via the numpy library. LOAD THE LIBRARY LIKE THIS.

In [22]:
import numpy
y=numpy.array([2,4,6,8])

In [23]:
y[0:3]


array([2, 4, 6])

In [33]:
y=numpy.linspace(0, 100, 26, dtype=int)

In [34]:
y[-1]

100

In [30]:
print (y
    )

[   0.    4.    8.   12.   16.   20.   24.   28.   32.   36.   40.   44.
   48.   52.   56.   60.   64.   68.   72.   76.   80.   84.   88.   92.
   96.  100.]


In [32]:
?numpy.arange

In [35]:
type (x)

str

In [36]:
type (y)

numpy.ndarray

In [37]:
type (y[1])

numpy.int64

## Welcome 2D array

In [41]:
a=numpy.array([[1,2],[2,3]])

In [43]:
print (a)


[[1 2]
 [2 3]]


In [50]:
a[0,:]

array([1, 2])

In [51]:
a[:,0]

array([1, 2])